trigger:
- main

resources:
  repositories:
  - repository: openWebUIRepo
    type: github
    endpoint: 'francislacroix (1)'
    name: francislacroix/open-webui
  - repository: openWebUIPipelinesRepo
    type: github
    endpoint: 'francislacroix (1)'
    name: francislacroix/open-webui-pipelines

variables:
  dockerRegistryServiceConnection: 'flcanchatacr' #'2c72e897-d1bb-405e-bd59-5935ee6868b6'
  containerRegistry: 'flcanchatacr.azurecr.io'
  openWebUIImageRepository: 'francislacroixopenwebui'
  openWebIUPipelinesImageRepository: 'francislacroixopenwebuipipelines'
  openWebUIDockerfilePath: '$(Build.SourcesDirectory)/openWebUIRepo/Dockerfile'
  openWebUIPipelinesDockerfilePath: '$(Build.SourcesDirectory)/openWebUIPipelinesRepo/Dockerfile'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - checkout: openWebUIRepo
    - checkout: openWebUIPipelinesRepo

    - task: Docker@2
      displayName: Build and push the Open-WebUI image
      inputs:
        command: buildAndPush
        repository: $(openWebUIImageRepository)
        dockerfile: $(openWebUIDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build and push the Open-WebUI Pipelines image
      inputs:
        command: buildAndPush
        repository: $(openWebIUPipelinesImageRepository)
        dockerfile: $(openWebUIPipelinesDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
