trigger:
- main

resources:
  repositories:
  - repository: open-webui
    type: github
    endpoint: 'francislacroix (1)'
    name: francislacroix/open-webui
  - repository: open-webui-pipelines
    type: github
    endpoint: 'francislacroix (1)'
    name: francislacroix/open-webui-pipelines

variables:
  dockerRegistryServiceConnection: 'flcanchatacr' #'2c72e897-d1bb-405e-bd59-5935ee6868b6'
  containerRegistry: 'flcanchatacr.azurecr.io'
  openWebUIImageRepository: 'francislacroixopenwebui'
  openWebIUPipelinesImageRepository: 'francislacroixopenwebuipipelines'
  openWebUIDockerfilePath: '$(Build.SourcesDirectory)/open-webui/Dockerfile'
  openWebUIPipelinesDockerfilePath: '$(Build.SourcesDirectory)/open-webui-pipelines/Dockerfile'
  dockerComposeFile: '$(Build.SourcesDirectory)/open-webui/open-webui-pipelines-compose.yml'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - checkout: open-webui
    - checkout: open-webui-pipelines

    - task: Docker@2
      displayName: Build and push the Open-WebUI image
      inputs:
        command: buildAndPush
        repository: $(openWebUIImageRepository)
        dockerfile: $(openWebUIDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build and push the Open-WebUI Pipelines image
      inputs:
        command: buildAndPush
        repository: $(openWebIUPipelinesImageRepository)
        dockerfile: $(openWebUIPipelinesDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Francis Lacroix - External'
        appName: 'openwebui'
        containers: |
          '$(openWebUIImageRepository):latest'
          '$(openWebIUPipelinesImageRepository):latest'